# Site settings
title: UK Accountant's Notes
email: your-email@accountant.com
description: > # this means to ignore newlines until "baseurl:"
  usefull info for accountants, auditors" 
# baseurl: site.github.url # the subpath of your site, e.g. /blog/
url: #"http://youraccountant.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url:
  - title: twitter
    url: 
  - title: linkedin
    url: 